### ISSUE TITLE
Error while upgrading 1.7.3.3->1.7.4.1

### ISSUE THREAD

**Issue by shaggee** [PrestaShop/autoupgrade#111] opened 2018-07-24 19:27 UTC
Tried newest version of autoupgrade v4.0.0-beta.4
Tried with difirent servers.
Tried with 1.7.3.3->1.7.4.0 with following results.
Last updates ended correctly. Now I cant upgrade 1.7.3.3 to newest version.

> [2018-07-24 20:13:50] All files upgraded. Now upgrading database...
[2018-07-24 20:13:50] [INTERNAL] /home/admin/domains/domain.com/public_html/vendor/composer/autoload_real.php line 61 - require(/home/admin/domains/domain.com/public_html/vendor/composer/../symfony/polyfill-php55/bootstrap.php): failed to open stream: No such file or directory
[2018-07-24 20:13:50] [INTERNAL] /home/admin/domains/domain.com/public_html/vendor/composer/autoload_real.php line 61 - require(/home/admin/domains/domain.com/public_html/vendor/composer/../symfony/polyfill-php54/bootstrap.php): failed to open stream: No such file or directory
[2018-07-24 20:13:51] [INTERNAL] /home/admin/domains/domain.com/public_html/config/autoload.php line 33 - require(/home/admin/domains/domain.com/public_html/config/../app/autoload.php): failed to open stream: No such file or directory
[2018-07-24 20:13:51] Migrating old setting file...
[2018-07-24 20:13:51] parameters file already exists!
[2018-07-24 20:13:51] Finished...
[2018-07-24 21:13:51] [INTERNAL] /home/admin/domains/domain.com/public_html/modules/autoupgrade/vendor/composer/ClassLoader.php line 444 - include(/home/admin/domains/domain.com/public_html/vendor/composer/../prestashop/smarty/Smarty.class.php): failed to open stream: No such file or directory
[2018-07-24 21:13:51] [INTERNAL] /home/admin/domains/domain.com/public_html/vendor/prestashop/smarty/Smarty.class.php line 1680 - include(/home/admin/domains/domain.com/public_html/vendor/prestashop/smarty/sysplugins/smarty_resource_custom.php): failed to open stream: No such file or directory
[2018-07-24 21:13:51] <div class="upgradeDbOk">[OK] SQL 1.7.4.0 SET SESSION sql_mode = ''</div>
[2018-07-24 21:13:51] <div class="upgradeDbOk">[OK] SQL 1.7.4.0 SET NAMES 'utf8'</div>
[2018-07-24 21:13:51] <div class="upgradeDbOk">[OK] SQL 1.7.4.0 ALTER TABLE `ps_order_detail` DROP KEY product_id, ADD KEY product_id (product_id, product_attribute_id)</div>
[2018-07-24 21:13:51] <div class="upgradeDbOk">[OK] SQL 1.7.4.0 INSERT IGNORE INTO `ps_hook` (`id_hook`, `name`, `title`, `description`, `position`) VALUES
  (NULL, 'actionAdministrationPageForm', 'Manage Administration Page form fields', 'This hook adds, update or remove fields of the Administration Page form', '1'),
  (NULL, 'actionAdministrationPageFormSave', 'Processing Administration page form', 'This hook is called when the Administration Page form is processed', '1'),
  (NULL, 'actionPerformancePageForm', 'Manage Performance Page form fields', 'This hook adds, update or remove fields of the Performance Page form', '1'),
  (NULL, 'actionPerformancePageFormSave', 'Processing Performance page form', 'This hook is called when the Performance Page form is processed', '1'),
  (NULL, 'actionMaintenancePageForm', 'Manage Maintenance Page form fields', 'This hook adds, update or remove fields of the Maintenance Page form', '1'),
  (NULL, 'actionMaintenancePageFormSave', 'Processing Maintenance page form', 'This hook is called when the Maintenance Page form is processed', '1'),
  (NULL, 'displayAdminEndContent', 'Administration end of content', 'This hook is displayed at the end of the main content, before the footer', '1')</div>
[2018-07-24 21:13:51] <div class="upgradeDbOk">[OK] PHP 1.7.4.0 : /* PHP:ps_1740_update_module_tabs(); */</div>
[2018-07-24 21:13:51] [INTERNAL] /home/admin/domains/domain.com/public_html/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php line 48 - Interface 'Symfony\Component\HttpKernel\RebootableInterface' not found

**Comment by PierreRambaud** [comment] 2018-07-24 19:57
Hi and really thanks for the feedback, we are looking for your bug and will be back really fast :)

@Quetzacoalt91 Look like it's the same bug as @rGaillard said, caches are sometimes cleaned.

**Comment by shaggee** [comment] 2018-07-24 20:04
Thats crazy.
I left 1.7.4.0 (interrupted and not completed) and started update to 1.7.4.1. 
And everything is ok. Update success.
Seems its only problem with 1.7.3.3->1.7.4.1 way.

**Comment by Quetzacoalt91** [comment] 2018-07-25 07:44
Hmm, about the cache issue, there is a PR I would rather see on the `develop` branch (= 1.7.5.0), but at least we know what's the cause.

In the meanwhile, about 
```
[2018-07-24 21:13:51] [INTERNAL] /home/admin/domains/domain.com/public_html/modules/autoupgrade/vendor/composer/ClassLoader.php line 444 - include(/home/admin/domains/domain.com/public_html/vendor/composer/../prestashop/smarty/Smarty.class.php): failed to open stream: No such file or directory
[2018-07-24 21:13:51] [INTERNAL] /home/admin/domains/domain.com/public_html/vendor/prestashop/smarty/Smarty.class.php line 1680 - include(/home/admin/domains/domain.com/public_html/vendor/prestashop/smarty/sysplugins/smarty_resource_custom.php): failed to open stream: No such file or directory
```
Note this has been fixed with https://github.com/PrestaShop/PrestaShop/pull/9345 on PS 1.7.4.2

**Comment by Lolcsi** [comment] 2018-07-25 07:57
I have same issue....

**Comment by Lolcsi** [comment] 2018-07-25 08:50
Problem solved. I use 1 click updater v4.0.0-beta.2. Update done!

**Comment by Quetzacoalt91** [comment] 2018-07-25 09:09
You mean `beta.2` works and `beta.4` brings this issue?

**Comment by Lolcsi** [comment] 2018-07-25 09:19
Yeah

**Comment by Lolcsi** [comment] 2018-07-25 12:40
but one more issue:
http://forge.prestashop.com/browse/BOOM-5982?attachmentOrder=asc

**Comment by Quetzacoalt91** [comment] 2018-07-25 13:06
In the issue you just linked, I already answered that I fixed it with https://github.com/PrestaShop/autoupgrade/pull/103

**Comment by shaggee** [comment] 2018-07-25 18:44
Also tried with Beta 2 but same results as beta 4 and 5....

**Comment by Lolcsi** [comment] 2018-07-26 13:05
I dont know whats wrong. it works for me

**Comment by PierreRambaud** [comment] 2018-07-26 13:42
You can retrieve the beta 4 here: https://github.com/PrestaShop/autoupgrade/releases

**Comment by tuhingr** [comment] 2018-07-29 14:52
I tried 1-click beta 5 by module page, not working.
How to install this module, please help!

**Comment by PierreRambaud** [comment] 2018-07-30 09:03
You must download the latest release and install it via the uploader in you admin :)

**Comment by Quetzacoalt91** [comment] 2018-08-06 09:36
The last issue remaining here could be caused by op-cache or another accelerator, and it has already been reported by #82 and #46. To avoid too many duplicates, I'm closing this one.

Thanks for your understanding

**Closed by Quetzacoalt91** 2018-08-06 09:36 UTC
