### ISSUE TITLE
parseFile: UndefinedMethodException

### ISSUE THREAD

**Issue by 99marco9** [PrestaShop/autoupgrade#154] opened 2018-08-29 12:24 UTC
**Describe the bug**
Actually I'm using prestashop 1.7.4.2  (I upgraded it from 1.7.3.2 using 1-click 4.0.0).
Today i tried to update the 1-click module from 4.0.0 to 4.1.0 but after that, every section of my back office return the following lines (error):

UndefinedMethodExceptionAttempted to call an undefined method named "parseFile" of class "Symfony\Component\Yaml\Parser".
--
in YamlFileLoader.php line 667
at YamlFileLoader->loadFile('/var/www/html/shopifex/app/config/config_dev.yml')in YamlFileLoader.php line 117
at YamlFileLoader->load('/var/www/html/shopifex/app/config/config_dev.yml', null)in DelegatingLoader.php line 40
at DelegatingLoader->load('/var/www/html/shopifex/app/config/config_dev.yml')in AppKernel.php line 137
at AppKernel->registerContainerConfiguration(object(DelegatingLoader))in Kernel.php line 774
at Kernel->buildContainer()in Kernel.php line 640
at Kernel->initializeContainer()in Kernel.php line 135
at Kernel->boot()in Kernel.php line 195
at Kernel->handle(object(Request), 1, false)in index.php line 88

 
**Upgrade environment:**
 - Version prestashop: 1.7.4.2
 - Way of upgrade: Web
 - Step concerned: upgrade 1-click module from 4.0.0 to 4.1.0

**Server:**
 - Web Server: Apache/2.4.29 (Ubuntu)
 - PHP Version: 7.0.31-1
 - Module Version: 4.1.0

**Comment by khouloudbelguith** [comment] 2018-08-29 12:27
Hi @99marco9,

We have this issue when the files of the module are being replaced by the 4.1 version. It appears that removing the module and reuploading it again fixes the issue. :)
I'm closing as it is a duplicate of https://github.com/PrestaShop/autoupgrade/issues/148

Best regards, Khouloud

**Comment by khouloudbelguith** [comment] 2018-08-29 12:27
Duplicate of https://github.com/PrestaShop/autoupgrade/issues/148

**Closed by khouloudbelguith** 2018-08-29 12:27 UTC
