### ISSUE TITLE
Error upgrading 1.6 to 1.7 when the store is in non-english

### ISSUE THREAD

**Issue by Guisardo** [PrestaShop/autoupgrade#158] opened 2018-09-05 01:22 UTC
**Describe the bug**
My store is in Spanish (Argentina); when I try to upgrade my store to 1.7, I get the error:

> [INTERNAL] /var/www/html/src/PrestaShopBundle/Install/LanguageList.php line 98 - Class 'PrestashopInstallerException' not found

**Upgrade environment (please complete the following information):**

Version you started from: 1.6.1.19
Version you upgrade to: 1.7.4.2 (major channel)
Way of upgrade: Web
Step concerned: upgrade DB
Displayed log

```
[OK] SQL 1.7.0.0 DELETE FROM `psks_hook` WHERE `name` IN ( 'displayProductTab', 'displayProductTabContent', 'displayBeforePayment', 'actionBeforeAuthentication', 'actionOrderDetail', 'actionProductListOverride', 'actionSearch', 'displayCustomerIdentityForm', 'displayHomeTab', 'displayHomeTabContent', 'displayPayment')
[OK] SQL 1.7.0.0 DELETE FROM `psks_hook_alias` WHERE `name` IN ( 'beforeAuthentication', 'displayProductTab', 'displayProductTabContent', 'displayBeforePayment', 'orderDetail', 'payment', 'productListAssign', 'search')
[OK] SQL 1.7.0.0 DELETE FROM `psks_configuration` WHERE `name` IN ( '_MEDIA_SERVER_2_', '_MEDIA_SERVER_3_', 'PS_ORDER_PROCESS_TYPE', 'PS_ADVANCED_PAYMENT_API', 'PS_ONE_PHONE_AT_LEAST', 'PS_SCENE_FEATURE_ACTIVE', 'PS_ADMINREFRESH_NOTIFICATION', 'PS_CUSTOMER_NWSL', 'PS_CACHEFS_DIRECTORY_DEPTH', 'PS_CART_REDIRECT', 'PS_COMPARATOR_MAX_ITEM', 'PS_STORES_DISPLAY_FOOTER', 'PS_STORES_SIMPLIFIED', 'PS_STORES_CENTER_LAT', 'PS_STORES_CENTER_LONG', 'PS_STORES_DISPLAY_SITEMAP', 'PS_CIPHER_ALGORITHM', 'PS_HTML_THEME_COMPRESSION', 'PS_JS_HTML_THEME_COMPRESSION', 'PS_LOGO_MOBILE', 'SHOP_LOGO_MOBILE_HEIGHT', 'SHOP_LOGO_MOBILE_WIDTH')
[OK] SQL 1.7.0.0 ALTER TABLE `psks_tab` ADD `icon` varchar(32) DEFAULT ''

Errores
[INTERNAL] /var/www/html/src/PrestaShopBundle/Install/LanguageList.php line 98 - Class 'PrestashopInstallerException' not found
```

**Expected behavior**
Fully upgrade to the 1.7 version without errors and with Spanish (Argentina) as main language

**Server (please complete the following information):**

Web Server: apache2
PHP Version: 7.1
Module Version 4.1.1
Additional context
This bug is easy to reproduce using docker and the following steps:

> * Raise a clean version of 1.6.1.19 version using https://hub.docker.com/r/prestashop/prestashop/
> * Complete the clean install
> * After the install, go to localizations and download all the Argentinian package
> * Set Spanish (Argentina) as main language
> * Go to modules and install version 4.1.1 of the 1 click upgrade
> * Open 1 click upgrade, disable all backups and set to upgrade default theme, set to set the default theme, disable no-native modules hit save
> * Put the site under mantainance
> * Hit upgrade to upgrade to 1.7
> ---- after a few minutes you should see the error
>

**Comment by khouloudbelguith** [comment] 2018-09-05 09:47
Hi @Guisardo,

I manage to reproduce the issue using the 1-click upgrade v4.1.1.
Upgrade from 1.6.1.17=> 1.7.4.2.
![image](https://user-images.githubusercontent.com/16067358/45085640-758c1b00-b101-11e8-8195-b0fff7151191.png)
@Quetzacoalt91 what do you think about this issue?

Best regards, Khouloud

**Comment by Quetzacoalt91** [comment] 2018-09-05 09:56
I haven't looked at the issue yet, but I already wanted to say that I love this kind of feedback, especially when our Docker image is used to reproduce it easily. :heart: 
Thank you @Guisardo

**Comment by Quetzacoalt91** [comment] 2018-09-06 14:56
Hi,

A pull request has just been opened (#163). The error was caused by unregistered classes.

However, I expected to get an exception during the process, but it actually completed.
I'll make another try, but it seems the changes made more fixes than I would think.

**Comment by Quetzacoalt91** [comment] 2018-09-07 09:42
I confirm 2 issues have been actually fixed.

I modified the content of the concerned method. I wanted to check if the langage was found or not:

```php
    /**
     * Set current language.
     *
     * @param string $iso Language iso
     */
    public function setLanguage($iso)
    {
        if (!in_array($iso, $this->getIsoList())) {
            trigger_error('Language ' . $iso . ' not found', E_USER_WARNING);
            throw new PrestashopInstallerException('Language ' . $iso . ' not found');
        }
        trigger_error('Language ' . $iso . ' found', E_USER_WARNING);
        $this->language = $iso;
    }
```

Running the upgrade brought me the following warning:

```
[2018-09-07 11:38:18] [INTERNAL] /var/www/html/src/PrestaShopBundle/Install/LanguageList.php line 101 - Language es found
```

With the next version of the module, you should be able to complete your upgrade @Guisardo

**Comment by Guisardo** [comment] 2018-09-07 17:46
@Quetzacoalt91 thanks for the help!!!! Can you set a date to the milestone? at least a broad one. It will be nice to know if I have to wait a year, a month o a few weeks :)
Best

**Comment by Quetzacoalt91** [comment] 2018-09-10 08:58
I created a beta version of the module with this fix. It can be downloaded here: https://github.com/PrestaShop/autoupgrade/releases

Feel free to try it, or wait for a stable version later. :)

As the issue is now fixed, I closing your issue.
Regards

**Closed by Quetzacoalt91** 2018-09-10 08:58 UTC
Labels: bug
