### ISSUE TITLE
1.6.1.23 to 1.7.5.1

### ISSUE THREAD

**Issue by aytekinazmi12** [PrestaShop/autoupgrade#304] opened 2019-04-30 13:34 UTC
Your message:

I am working with 1-click upgrade module. I get the following error. What is the solution?

[INTERNAL] /var/www/vhosts/website.com/httpdocs/vendor/smarty/smarty/libs/sysplugins/smarty_internal_extension_handler.php line 168 - Error: Class 'Smarty_Internal_Undefined' not found #0 /var/www/vhosts/website.com/httpdocs/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatebase.php(277): Smarty_Internal_Extension_Handler->__get('registerPlugin') #1 /var/www/vhosts/website.com/httpdocs/config/smarty.config.inc.php(125): Smarty_Internal_TemplateBase->registerPlugin('function', 'toolsConvertPri...', Array) #2
/var/www/vhosts/website.com/httpdocs/config/smartyadmin.config.inc.php(35): smartyRegisterFunction(Object(Smarty), 'function', 'toolsConvertPri...', 'toolsConvertPri...') #3 /var/www/vhosts/website.com/httpdocs/config/smarty.config.inc.php(57): require_once('/var/www/vhosts...') #4 /var/www/vhosts/website.com/httpdocs/config/config.inc.php(202): require_once('/var/www/vhosts...') #5 /var/www/vhosts/website.com/httpdocs/modules/autoupgrade/classes/UpgradeContainer.php(475): require_once('/var/www/vhosts...') #6 /var/www/vhosts/website.com/httpdocs/modules/autoupgrade/classes/TaskRunner/AbstractTask.php(120): PrestaShopModuleAutoUpgradeUpgradeContainer->initPrestaShopCore() #7 /var/www/vhosts/website.com/httpdocs/modules/autoupgrade/classes/TaskRunner/Upgrade/UpgradeDb.php(75): PrestaShopModuleAutoUpgradeTaskRunnerAbstractTask->init() #8 /var/www/vhosts/website.com/httpdocs/adminyd/autoupgrade/ajax-upgradetab.php(51): PrestaShopModuleAutoUpgradeTaskRunnerUpgradeUpgradeDb->init() #9 {main}

**Comment by Quetzacoalt91** [comment] 2019-05-08 16:54
This issue may be fixed with #306. Please wait for the v4.8.0 and please try again.

**Closed by Quetzacoalt91** 2019-05-08 16:54 UTC

**Comment by aytekinazmi12** [comment] 2019-05-08 19:17
When is it published?

**Comment by Quetzacoalt91** [comment] 2019-05-09 07:30
I expect it to be released next week. I need the QA team to review the module before getting it published.

**Comment by aytekinazmi12** [comment] 2019-05-09 07:47
thanks. Waiting Impatiently.

**Comment by aytekinazmi12** [comment] 2019-05-10 07:03
Hi Thomas,

Thanks for the 4.8 version, but I'm having a different problem right now. Can you help?

Error Messages:

[INTERNAL] /var/www/vhosts/website.com/httpdocs/vendor/smarty/smarty/libs/sysplugins/smarty_internal_extension_handler.php line 168 - Error: Class 'Smarty_Internal_Undefined' not found #0 /var/www/vhosts/website.com/httpdocs/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatebase.php(277): Smarty_Internal_Extension_Handler->__get('registerPlugin') #1 /var/www/vhosts/website.com/httpdocs/config/smarty.config.inc.php(125): Smarty_Internal_TemplateBase->registerPlugin('function', 'toolsConvertPri...', Array) #2 /var/www/vhosts/website.com/httpdocs/config/smartyadmin.config.inc.php(35): smartyRegisterFunction(Object(Smarty), 'function', 'toolsConvertPri...', 'toolsConvertPri...') #3 /var/www/vhosts/website.com/httpdocs/config/smarty.config.inc.php(57): require_once('/var/www/vhosts...') #4 /var/www/vhosts/website.com/httpdocs/config/config.inc.php(202): require_once('/var/www/vhosts...') #5 /var/www/vhosts/website.com/httpdocs/modules/autoupgrade/classes/UpgradeContainer.php(499): require_once('/var/www/vhosts...') #6 /var/www/vhosts/website.com/httpdocs/modules/autoupgrade/classes/TaskRunner/AbstractTask.php(120): PrestaShop\Module\AutoUpgrade\UpgradeContainer->initPrestaShopCore() #7 /var/www/vhosts/website.com/httpdocs/modules/autoupgrade/classes/TaskRunner/Upgrade/UpgradeDb.php(75): PrestaShop\Module\AutoUpgrade\TaskRunner\AbstractTask->init() #8 /var/www/vhosts/website.com/httpdocs/adminyd/autoupgrade/ajax-upgradetab.php(52): PrestaShop\Module\AutoUpgrade\TaskRunner\Upgrade\UpgradeDb->init() #9 {main}

**Comment by Quetzacoalt91** [comment] 2019-05-10 08:07
I may already know the answer, but could you tell me if the file `vendor/smarty/smarty/libs/sysplugins/smarty_internal_undefined.php` exists in your shop when the error occurs?

If yes, this may be caused by some cached data, but I can't figure out which one. In the meantime, note you can try to run the database upgrade manually by calling the file `<install-folder>/upgrade/uprade.php`

**Comment by aytekinazmi12** [comment] 2019-05-10 08:56
Yes. There is a file named smarty_internal_undefined.php.

https://www.website.com/install/upgrade/upgrade.php I have access to this address. but it was not successful.

**Comment by aytekinazmi12** [comment] 2019-05-11 11:04
Can you help me?
