### ISSUE TITLE
Update ps 1.7.5 > 1.7.6 

### ISSUE THREAD

**Issue by antoniopineapple** [PrestaShop/autoupgrade#337] opened 2019-08-14 06:34 UTC
when i click on 1-click update button after a while appears error 500
log:
*ERROR* 	v1.7.5.0	2019/08/13 - 00:01:01: Invalid category vars at line 384 in file classes/Link.php
*ERROR* 	v1.7.5.0	2019/08/13 - 00:02:02: Invalid category vars at line 384 in file classes/Link.php
*ERROR* 	v1.7.5.0	2019/08/13 - 00:03:03: Invalid category vars at line 384 in file classes/Link.php
*ERROR* 	v1.7.5.0	2019/08/13 - 00:04:04: Invalid category vars at line 384 in file classes/Link.php
*ERROR* 	v1.7.5.0	2019/08/13 - 00:06:39: Invalid category vars at line 384 in file classes/Link.php
*ERROR* 	v1.7.5.0	2019/08/13 - 00:07:39: Invalid category vars at line 384 in file classes/Link.php
*ERROR* 	v1.7.5.0	2019/08/13 - 00:07:39: Invalid category vars at line 384 in file classes/Link.php
*ERROR* 	v1.7.5.0	2019/08/13 - 00:07:57: Invalid category vars at line 384 in file classes/Link.php
*ERROR* 	v1.7.5.0	2019/08/13 - 00:08:40: Invalid category vars at line 384 in file classes/Link.php
*ERROR* 	v1.7.5.0	2019/08/13 - 00:08:40: Invalid category vars at line 384 in file classes/Link.php
*ERROR* 	v1.7.5.0	2019/08/13 - 00:08:58: Invalid category vars at line 384 in file classes/Link.php
*ERROR* 	v1.7.5.0	2019/08/13 - 00:09:41: Invalid category vars at line 384 in file classes/Link.php
*ERROR* 	v1.7.5.0	2019/08/13 - 00:09:41: Invalid category vars at line 384 in file classes/Link.php
*ERROR* 	v1.7.5.0	2019/08/13 - 00:09:59: Invalid category vars at line 384 in file classes/Link.php

**Upgrade environment (please complete the following information):**
 - Version you started from: [e.g. 1.7.1.0]
 - Version you upgrade to: [e.g. 1.7.4.0]
 - Way of upgrade: Web
 - Step concerned: [e.g upgrade DB] 

**Displayed log**
```
Insert upgrade / rollback log here
```

**Expected behavior**

**Screenshots**

**Server (please complete the following information):**
 - Web Server: [e.g. Apache / Nginx / IIS]
 - PHP Version: [e.g. 7.1]
 - Module Version [e.g. 4.0.0]

**Additional context**

**Comment by mariem-abid** [comment] 2019-08-16 12:52
Hi @antoniopineapple,

Your ticket is a duplicate of #15107
So, I close it.
Thanks!

**Comment by mariem-abid** [comment] 2019-08-16 12:52
Duplicate of #15107

**Closed by mariem-abid** 2019-08-16 12:52 UTC
