### ISSUE TITLE
Google Search Console product failures

### ISSUE THREAD

**Issue by ColindaHeeren** [PrestaShop/autoupgrade#314] opened 2019-05-11 14:46 UTC
While optimizing my Prestashop website using google search console I keep getting the following error messages:
'offers', 'review' or 'aggregateRating' must be specified
'ratingCount' or 'reviewCount' must be specified

Relates to current released version 1.7.5.2

I would like to have an error free website, so please advise what needs to be done to resolve these error messages

**Comment by Quetzacoalt91** [comment] 2019-05-13 08:00
Hello,

This issue, if confirmed, is not related to the autoupgrade module. This could be caused by the theme you use.

You should contact the theme developer instead, or if you're using the `classic` theme create an issue on [PrestaShop/PrestaShop](https://github.com/PrestaShop/PrestaShop/issues/new/choose).

I'm closing as I can't do anything for you in this project.
Regards

**Closed by Quetzacoalt91** 2019-05-13 08:00 UTC
