### ISSUE TITLE
Bad characters encadage ("&quot;")  into module description text

### ISSUE THREAD

**Issue by Klemart3D** [PrestaShop/autoupgrade#283] opened 2019-02-22 16:49 UTC
**Describe the bug**
After update module v4.5.1 -> v4.6.0, some texts are badly encoded (HTML code is not interpreted), see attach.

**Server**
 - Web Server: Nginx
 - PHP Version: 7.1
 - Prestashop Version: 1.7.5.0
 - Module Version 4.6.0

![Module description text](https://user-images.githubusercontent.com/7419525/53257307-15e2f580-36ca-11e9-87a1-1e8e431099b2.png)

**Comment by Quetzacoalt91** [comment] 2019-02-27 14:05
Thanks for this report, I had a look at this and this seems to be caused by a escaping done from PS 1.7.

I opened #285 to fix that visual issue.

**Comment by Quetzacoalt91** [comment] 2019-03-08 14:59
Closed via #285

**Closed by Quetzacoalt91** 2019-03-08 14:59 UTC
