### ISSUE TITLE
Upgarde NOK from 1.6.1.22 to 1.7.5.0-beta1

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/autoupgrade#184] opened 2018-10-22 16:50 UTC
**Describe the bug**
There's errors after upgrade from 1.6.1.22 to 1.7.5.0-beta1, using the 1-click upgrade v4.4.0

**Upgrade environment (please complete the following information):**
 - Version you started from: 1.6.1.22
 - Version you upgrade to: 1.7.5.0-beta1
 - Using the local archive

**Displayed log**
```
[INTERNAL] /var/www/html/upgrade/16122/classes/Link.php line 835 - TypeError: Argument 1 passed to LinkCore::searchRouteFromRouter() must be an instance of Symfony\Component\Routing\RouterInterface, null given, called in /var/www/html/upgrade/16122/classes/Link.php on line 815
#0 /var/www/html/upgrade/16122/classes/Link.php(815): LinkCore->searchRouteFromRouter(NULL, 'AdminPsThemeCus...')
#1 /var/www/html/upgrade/16122/modules/ps_themecusto/ps_themecusto.php(61): LinkCore->getAdminLink('AdminPsThemeCus...')
#2 [internal function]: ps_themecusto->__construct()
#3 /var/www/html/upgrade/16122/src/Core/Foundation/IoC/Container.php(130): ReflectionClass->newInstance()
#4 /var/www/html/upgrade/16122/src/Core/Foundation/IoC/Container.php(163): PrestaShop\PrestaShop\Core\Foundation\IoC\Container->makeInstanceFromClassName('ps_themecusto', Array)
#5 /var/www/html/upgrade/16122/src/Core/Foundation/IoC/Container.php(176): PrestaShop\PrestaShop\Core\Foundation\IoC\Container->doMake('ps_themecusto', Array)
#6 /var/www/html/upgrade/16122/src/Adapter/ServiceLocator.php(65): PrestaShop\PrestaShop\Core\Foundation\IoC\Container->make('ps_themecusto')
#7 /var/www/html/upgrade/16122/classes/module/Module.php(1134): PrestaShop\PrestaShop\Adapter\ServiceLocator::get('ps_themecusto')
#8 /var/www/html/upgrade/16122/classes/module/Module.php(1113): ModuleCore::coreLoadModule('ps_themecusto')
#9 /var/www/html/upgrade/16122/classes/module/Module.php(1872): ModuleCore::getInstanceByName('ps_themecusto')
#10 /var/www/html/upgrade/16122/classes/module/Module.php(1826): ModuleCore::checkModuleFromAddonsApi('ps_themecusto')
#11 /var/www/html/upgrade/16122/classes/module/Module.php(1721): ModuleCore::generateTrustedXml()
#12 /var/www/html/upgrade/16122/classes/module/Module.php(1379): ModuleCore::isModuleTrusted('blockcurrencies')
#13 /var/www/html/upgrade/16122/modules/autoupgrade/classes/TaskRunner/Upgrade/UpgradeModules.php(158): ModuleCore::getModulesOnDisk()
#14 /var/www/html/upgrade/16122/modules/autoupgrade/classes/TaskRunner/Upgrade/UpgradeModules.php(45): PrestaShop\Module\AutoUpgrade\TaskRunner\Upgrade\UpgradeModules->warmUp()
#15 /var/www/html/upgrade/16122/admin-dev/autoupgrade/ajax-upgradetab.php(52): PrestaShop\Module\AutoUpgrade\TaskRunner\Upgrade\UpgradeModules->run()
#16 {main}
```

**Screenshots**
![image](https://user-images.githubusercontent.com/16067358/47305901-34a58280-d62b-11e8-8701-759c1ce31df9.png)

**Server (please complete the following information):**
 - Web Server: Apache 
 - PHP Version: 7.1
 - Module Version 4.4.0

**Comment by Quetzacoalt91** [comment] 2018-10-22 17:09
cc @jolelievre 

To be confirmed, but it seems this method does not exist anymore in 1.7.5.x branch. The actual beta version should prevent this error to occur.

**Comment by jolelievre** [comment] 2018-10-23 07:45
@Quetzacoalt91 that's the thing I don't know how this method can bug since it does not exist any more.. so debugging it is even trickier ^^
more seriously where does it come from, this method was introduced for a few times in 1.7.5 development but it is not present in the beta build, where does the autoupgrade go fetch this beta version?

**Comment by Quetzacoalt91** [comment] 2018-10-23 10:56
![capture du 2018-10-23 11-53-04](https://user-images.githubusercontent.com/6768917/47355805-408c5580-d6ba-11e8-94d4-c05905cb0b05.png)

I'm sorry, but I cannot reproduce the issue when using the beta release provided by @jolelievre. You should double check the release you used, because the code written in your screenshot was removed from the `1.7.5.x` branch.

Closing as "Cannot reproduce".

**Closed by Quetzacoalt91** 2018-10-23 10:56 UTC
Labels: bug
