### ISSUE TITLE
Error 500 after Upgrade from 4.0 to 4.1

### ISSUE THREAD

**Issue by jkdi** [PrestaShop/autoupgrade#150] opened 2018-08-27 16:11 UTC
Hi,
i'm upgrading Module 4.0 to 4.1 today with the normal Prestashop updater in Backend. And now i can't login anymore in the backend!!!!!!! its really bad. i became an error 500:

```
Oops! An Error Occurred

The server returned a "500 Internal Server Error".

Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused.
```

the nginx error log say's now:

```
2018/08/27 17:27:28 [error] 2002#2002: *11557 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Cannot use object of type Symfony\Component\HttpFoundation\ParameterBag as array in /var/websites/xxx/src/Adapter/Security/Admin.php:82
Stack trace:
#0 /var/websites/xxx/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php(212): PrestaShop\PrestaShop\Adapter\Security\Admin->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher))
#1 /var/websites/xxx/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php(44): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent))
#2 /var/websites/xxx/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(127): Symfony\Component\EventDispatcher\EventDispatcher->dispat" while reading response header from upstream, client: xxx.xx.xx.xx, server: xxx.de, request: "GET /adminxxx/ HTTP/2.0", upstream: "fastcgi://unix:/run/php/php7.0-fpm.sock:", host: "www.xxx.de"

**Comment by khouloudbelguith** [comment] 2018-08-27 16:17
Hi @jkdi,

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
- host
- server setup and configuration
- PrestaShop version (source)
- debug mode report
- PHP error logs
- apache error log
- javascript console log

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

Best regards, Khouloud

**Comment by jkdi** [comment] 2018-08-27 16:37
Prestashop Debug Mode says:

`

(1/1) UndefinedMethodExceptionAttempted to call an undefined method named "parseFile" of class "Symfony\Component\Yaml\Parser".
--
in YamlFileLoader.php line 667
at YamlFileLoader->loadFile('/var/websites/xxx/app/config/config_dev.yml')in YamlFileLoader.php line 117
at YamlFileLoader->load('/var/websites/xxx/app/config/config_dev.yml', null)in DelegatingLoader.php line 40
at DelegatingLoader->load('/var/websites/xxx/app/config/config_dev.yml')in AppKernel.php line 137
at AppKernel->registerContainerConfiguration(object(DelegatingLoader))in Kernel.php line 774
at Kernel->buildContainer()in Kernel.php line 640
at Kernel->initializeContainer()in Kernel.php line 135
at Kernel->boot()in Kernel.php line 195
at Kernel->handle(object(Request), 1, false)in index.php line 88

`

**Comment by jkdi** [comment] 2018-08-27 16:40
- Prestashop 1.7.4.2
 - Web Server: Nginx 1.10.3
 - PHP Version: 7.0
 - Module Version 4.1

php-error log is empty

**Comment by Quetzacoalt91** [comment] 2018-08-28 08:31
Hi,

Indeed, we have this issue when the files of the module are being replaced by the 4.1 version. It appears that removing the module and reuploading it again fixes the issue. :)

I'm closing as it is a duplicate of #148.

**Closed by Quetzacoalt91** 2018-08-28 08:31 UTC
Labels: bug
