### ISSUE TITLE
upgrade from 1.6.1.22 to 1.7.4.3

### ISSUE THREAD

**Issue by yoanmarchal** [PrestaShop/autoupgrade#186] opened 2018-11-03 17:05 UTC
**Describe the bug**
Accès forbiden on some admin pages after update ( i got super-admin level)

**Upgrade environment (please complete the following information):**
 - Version you started from: 1.6.1.22 (fresh install)
 - Version you upgrade to: 1.7.4.3
 - Way of upgrade: Web
 - Step concerned: upgrade DB

**Expected behavior**
update db in order 

**Screenshots**
![bug-prestashop-migration](https://user-images.githubusercontent.com/605313/47955078-e8dfcb00-df92-11e8-897c-a9262ef16f5e.png)

**Server (please complete the following information):**
 - Web Server: php
 - PHP Version: 7.2.2
 - Module Version 4.4.0

**Comment by khouloudbelguith** [comment] 2018-11-05 09:39
Hi @yoanmarchal,

To fix this issue you need to replace 'ps_access' table in DB with the one from clean PS1.7 installation.
Your ticket is a duplicate of https://github.com/PrestaShop/autoupgrade/issues/100.
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2018-11-05 09:39
Duplicate of #100

**Closed by khouloudbelguith** 2018-11-05 09:39 UTC

**Comment by yoanmarchal** [comment] 2018-11-05 10:52
i'm sorry but it was ps_authorization_role the problème, indeed it resolve my probleme manualy but i still think it's a bug, since autoupgrade dont do the job correctly
